version: '3.0'

services:
  web:
    image: lgouveia/node-jenkins:latest
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3000"
